name: unit-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: gtest-permission
      run: chmod a+x Hotel_Booking/all.out 
    
